### ISSUE TITLE
Not recording sessions created with ProxyCommand  and ssh -W option

### ISSUE THREAD

**Issue by fllaca** [Guimove/terraform-aws-bastion#50]
Connecting to servers using `ProxyCommand` and `ssh -W $host:$port` bypasses the recording.

Example ssh config:

```
Host myserver.mycompany.com
    ProxyCommand ssh bastion.mycompany.com -W %h:%p
```

Is there a way to record the actions executed in the remote servers if connecting this way?

Thanks for this great project!

**Comment by Guimove** [comment]
Hello,

Yes I know this issue, that's why initialy I disabled the AllowTcpForwarding to forbid the ProxyCommand because we are not able to log the session in this mode.
But for some reason, in need the AllowTcpForwarding like for SSH Tunneling for example.

I don't know if their is any way to resolve this, I've to check.

Thanks 😄
